### ISSUE TITLE
LP IFI 2024 > Desktop > Appel à don

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#15]
<img width="954" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/460758b2-7fe4-46ae-a748-9c4322f26295">

- Sur petit écran, problème au niveau de la taille des textes. Il faut que le titre soit de la même taille que les titres "Contre le cancer..." qui se trouvent plus haut
- Les CTA doivent avoir la même largeur
- Le texte dans le CTA doit être tout en majuscule
- il faut la même animation sur les CTA que l'animation qui est sur les CTA du bloc défiscalisation (les CTA qui s'allongent au roll over)

**Comment by Sahani14** [comment]
- Sur petit écran, problème au niveau de la taille des textes. Il faut que le titre soit de la même taille que les titres "Contre le cancer..." qui se trouvent plus haut

- Au roll over sur un des CTA, l'autre ne doit pas bouger
Preview :
https://github.com/adfinitas-app/curie-ifi20/assets/150721779/140dc442-5fef-49cc-bcd5-b34ddc6e599d
Maquette : 
https://github.com/adfinitas-app/curie-ifi20/assets/150721779/adf00a7f-00c8-4f46-acaa-8d446df009c4

- Mettre les liens de redirection

**Comment by jean-baptisteAZAN** [comment]
pour le rollhover des deux boutons, je ne faire en sorte que la position de l'autre bouton reste fixe, j'ai tout tester , ca ne rend pas bien de mon coté, je peux par contre faire en sorte qu'ils scalent sans bouger l'autre

**Comment by Sahani14** [comment]
Et si on les espace un peu de base quand ils sont statiques ? du coup au roll over ça ne pousserait pas forcément l'autre CTA non ?

**Comment by Sahani14** [comment]
@jean-baptisteAZAN sinon on va changer l'animation. Pour ces 2 boutons, est-ce-que tu peux mettre l'animation des CTA qui grossissent au roll over comme les CTA don de cette LP ? https://nourrirlemonde.ccfd-terresolidaire.org/

**Comment by jean-baptisteAZAN** [comment]
c'est le mieux je pense !
