### ISSUE TITLE
LP IFI 2024 > Desktop > Safari

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#18]
- sur safari, la typo n'est pas bonne 
- le tampon IFi est cropé
<img width="1188" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/b37c4e2b-97a8-4942-9eea-d33db391f61a">

- il y a un soucis au niveau du calendrier fiscal
<img width="1090" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/336aef77-4dc0-4767-8b34-ca6190716ccc">
<img width="981" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/7bfbacb2-dc46-4f7f-b9ba-51a7575b4aa0">

**Comment by jean-baptisteAZAN** [comment]
je n'ai pas reussi a reproduire ce bug sur browserstack de mon coté, tu as d'autres infos par hasard ?

**Comment by Sahani14** [comment]
Mon mac : 
<img width="574" alt="Capture d’écran 2024-04-03 à 16 54 46" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/3a1b24b6-24d8-4fda-b7de-3a6407e6010d">

Ma version Safari : 
<img width="258" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/3a6d9d1f-2d85-46b8-b2fc-b25aa5881a83">

**Comment by Sahani14** [comment]
@jean-baptisteAZAN est-ce-que tu as trouvé une solution à ça ? je reproduis aussi le bug sur browserstack

**Comment by Sahani14** [comment]
- Mac > Sonoma > Safari 17,3 > 1920x1080 --> Pbme du bandeau violet qui passe sur les chercheurs sur 
![Capture d’écran 2024-04-09 à 14 40 35](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/aa3f066f-eb82-4d44-aa32-16f84b080f22)

- Mac > Ventura > Safari 16,5 > 1280x1024
- Mac > Monterey > Safari 15,6 > 1280x1024
- Mac > Monterey > Safari 14,1 > 1280x1024
--> le tampon IFI passe sur le visage de la chercheuse
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/8af7b506-78ea-4ab6-8bf9-99d3787fe58f)

- Mac > Catalina > Safari 13,1 > toutes les résolutions
--> les CTA sont trop collés 
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/e6e026f8-905d-40a3-a31e-8fc4f7efbf92)

--> le chevron est trop collé au texte
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/3b713f52-df46-4298-a5f4-c169d541b5a0)

--> les éléments de la partie projet sont trop collés les uns aux autres / pareil pour le bloc d'appel à don
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/dda229c6-7c93-4d3b-827c-a9fb3d9effe6)

![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/d68d0b1a-7406-4d93-bb7d-571fccab3701)

**Comment by Sahani14** [comment]
- Pbme du bandeau violet qui passe sur les chercheurs sur Mac > Sonoma > Safari 17,3 > 1920x1080
--> pas OK

- les éléments du bloc d'appel à don sont trop collés sur Mac > Catalina > Safari 13,1 > toutes les résolutions
--> pas OK

- les paragraphes l'enjeu et l'innovation des projets 1 et 2 ne sont pas alignés sur Mac > toutes les versions > Safari 13,1 > toutes les résolutions
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/7babd4ff-7ce4-4754-b660-9c8dc5801f2a)

**Comment by jean-baptisteAZAN** [comment]
alignement des textes : ok

**Comment by jean-baptisteAZAN** [comment]
<img width="1442" alt="Screenshot 2024-04-10 at 17 48 30" src="https://github.com/adfinitas-app/curie-ifi20/assets/114654392/ea2d6f10-9fdb-46ba-a0f4-6bad5427ea84">
<img width="1614" alt="Screenshot 2024-04-10 at 17 48 52" src="https://github.com/adfinitas-app/curie-ifi20/assets/114654392/9194e69d-bddb-41e4-a2a7-bac0b45d11ec">

j'ai tester toute les resolution sur safari 17.3 et je n'arrive pas a reproduire l'overflow sur les chercheurs, tu peux me faire une video stp ? si jamais tu peux me call sur slack

**Comment by jean-baptisteAZAN** [comment]
les elements du bloc d'appel a don c'est ca ? 


<img width="1041" alt="Screenshot 2024-04-10 at 17 55 23" src="https://github.com/adfinitas-app/curie-ifi20/assets/114654392/5b7bf855-6fbc-4e12-8ca0-501c39be4d03">

**Comment by Sahani14** [comment]
**Mac > Catalina > Safari 13,1 > toutes les résolutions :** 
- les éléments du bloc contact sont trop collés : pictos, numéro et adresse email
- les 4 éléments du bloc info pratiques sont trop collés, les espacer en largeur
<img width="618" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/528e3b0c-8d86-4f95-a36f-27a1cc7a618e">

L'alignement n'est tjrs pas optimal sur les 2 paragraphes "enjeu" et "innovation" du projet # : 
<img width="685" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/38d6b52e-525e-423f-be47-117315c6fe1d">
