### ISSUE TITLE
LP IFI 2024 > Desktop > Firefox

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#19]
- sur Firefox, la typo n'est pas bonne : 
<img width="1391" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/64b489e5-b779-4677-85d7-5b3c26d86693">

**Comment by jean-baptisteAZAN** [comment]
pareil, chez moi ca a l'air d'etre la bonne police, si tu as d'autres infos comme tas version etc...

**Comment by Sahani14** [comment]
Mon mac : 
<img width="574" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/93af0be3-e7fe-4839-89a0-6f120c145399">

Ma version firefox : 
<img width="706" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/92e8a2d3-d054-4435-8953-14b4322d4e87">
