### ISSUE TITLE
LP IFI 2024 > Desktop > responsive header

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#2]
Sur petit écran (Mac 13 pouces), j'ai toujorus un problème d'affichage car la bande violette passe sur le visuel des chercheurs et sur le tampon IFI.

Lien de preview : 
<img width="1419" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/e992547e-da80-450a-8b43-0b3cf6eb0c05">

Maquette : 

<img width="976" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/a70d7fcc-1dd5-4966-918f-634f05c5b43f">

**Comment by jean-baptisteAZAN** [comment]
alors je vais pouvoir rendre visible le logo ifi 24 orange mais si je diminue la hauteur du bandeau violet (celui en bas de l'image) le texte sera vraiment trop petit. Si j'augmente la hauteur de l'image on dépassera la ligne de flottaison.

**Comment by Sahani14** [comment]
Le rendu sur petit écran est mieux qu'avant mais le tampon IFI est un peu trop gros et le bandeau violet et le bandeau violet cache encore un peu trop le visages des chercheurs.
<img width="1430" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/45d3427c-6e84-447c-a4ce-f1cc0f717b96">

Le rendu sur grand écran n'est plus ok car le tampon IFI passe sous le bandeau violet et le bandeau violet cache encore un peu trop le visages des chercheurs.
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/8d6d08e3-be63-4598-9268-5aa7753cdb1c)

Je pense qu'il faudrait un légèrement diminuer le texte. Ce serait possible ?
