### ISSUE TITLE
LP IFI 2024 > Mobile > Android / Chrome > Header

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#22]
- l'animation n'est pas la bonne --> mettre la même animation que sur la version desktop
- le chevron n'est pas visible quand on arrive sur la LP
- chevron n'est pas cliquable
![Screenshot_2024-04-03-17-29-44-77_40deb401b9ffe8e1df2f1cc5ba480b12 (1)](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/496461d7-60bb-4be1-baf3-2c02cd834d3d)

Remarque sur l'ensemble de la LP : 
- la typo n'est pas la bonne

**Comment by Sahani14** [comment]
Pas OK de mon côté, voici le rendu sur un Android > Realmi 8 > chrome : 

![Screenshot_2024-04-09-14-19-53-38_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/84b2cf03-63d4-4b10-b402-b979cd9355c7)

Et sur Android > Realmi 8 > firefox

![Screenshot_2024-04-09-14-21-37-68_3aea4af51f236e4932235fdada7d1643](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/cb7da7aa-67cf-412f-b917-c28caec87c9e)

**Comment by Sahani14** [comment]
Sur chrome il manque le soulignage des mots "nouvelles perspectives"

Sur firefox il manque le soulignage du mot "perspectives"

**Comment by jean-baptisteAZAN** [comment]
c'est good :)

**Comment by Sahani14** [comment]
Merci :) 

Possible d'avoir un soulignage un tout petit peu moins collé au texte ? Sur android comme sur iphone
<img width="246" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/7702366e-de35-4f0c-9eeb-4e1ffdc9b17f">
