### ISSUE TITLE
LP IFI 2024 > Mobile > Android / Chrome > Pop in impôt sur les sociétés

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#24]
- même problème avec l'animation sur le CTA
- il manque le lien de redirection
- il manque la croix de fermeture
![1000068358 (1)](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/f02eaf03-1c34-4013-9f66-2db08cd32438)

**Comment by jean-baptisteAZAN** [comment]
j'ai enleve la crois car ca ne rendait pas bien, par contre j'ai fait en sorte que si on click hors de la popup, elle se ferme, qu'en penses tu ?

**Comment by Sahani14** [comment]
Le CTA passe par dessus le graphique : 

![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/2be90c73-0b26-4be5-a393-a23191dd2008)

- Android > Motorola > Moto edge 40 Neo > chrome
- Redmi > Redmi Note 12 4G > edge
- Xiaomi > firefox
- Apple > Iphone 11 > chrome
- Apple > Iphone 12 mini > safari
