### ISSUE TITLE
LP IFI 2024 > Mobile > Android / Chrome > 

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#26]
- rajouter un fond flouté
- la pop in calculatrice est trop grosse, ça dépasse de l'écran sur la droite
![1000068360 (1)](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/3aab0484-a8ba-46a4-bb39-e42dec59a585)
- il manque la croix de fermeture
- les "€" ne sont pas de la même taille
- quand la calculatrice est ouverte, si on clique sur "Les projets soutenus", il faut que ça ferme la pop in calculette et qu'on arrive à l'ancre projet

**Comment by jean-baptisteAZAN** [comment]
j'ai traité le reste mais ou est ce que tu prévois la croix ?

**Comment by Sahani14** [comment]
Les retours suivants ne sont pas OK : 
- rajouter un fond flouté
- quand la calculatrice est ouverte, si on clique sur "Les projets soutenus", il faut que ça ferme la pop in calculette et qu'on arrive à l'ancre projet

Concernant la croix de fermeture, possible de la mettre ici ?
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/aad662df-3c9f-45f4-aa9d-a9fcb2a5e068)

Autres retours : 
- possible de réduire le menu, tu peux te baser sur la taille du menu de la LP ifi.curie.fr 
- quand on clique sur le menu > clique sur la calculatrice > ferme le menu > réouvre le menu ==> il ne faut pas que la calculatrice s'ouvre automatiquement. Il faut que ça "éouvre seulement le menu avec "les projets soutenus" et "calculer sa réduction d'impôt"
- sur le 3ème champ, les € ne sont pas au même niveau. Certains sont + collés au bord que d'autres

**Comment by jean-baptisteAZAN** [comment]
j'ai mis el flou qui regel pas mal de soucis et ajusté les symboles euros ! La hauteur du bandeau est la meme aussi

**Comment by Sahani14** [comment]
Je trouve le rendu bien mieux, merci 😊
