### ISSUE TITLE
LP IFI 2024 > Mobile > Android / Chrome > Partie projets

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#28]
- il manque l'effet ombre autour de la partie projet
- La photo du chercheur sont un peu étirées : 
![1000068363 (2)](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/39cb093a-78c9-4c63-ba42-95d6eb59c0ee)

- il faut les mêmes flèches "suivant" et "précédent" comme sur la LP desktop

**Comment by Sahani14** [comment]
Sur Samsung S8 : 
- les bullet points ne sont pas alignées correctement au texte 
<img width="246" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/b768af2d-b538-48b7-9709-6293aa85029b">

- le bouton suivant est trop collé au bouton réduire  
<img width="234" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/76eb1879-2bdc-4f07-8ffb-7a630ca6b92a">

Mêmes retours sur : 
- One plus 11R > chrome
- Xiaomi Redmi > firefox
- Huawei P30 > Edge

**Comment by Sahani14** [comment]
Est-ce-que tu peux mettre la même dimension de visuel pour les chercheurs stp ? En te basant sur le visuel du projet 1

**Comment by jean-baptisteAZAN** [comment]
je l'ai fait pour le projet 2 mais pour le projet 3 ca rend l'image du cherche completement compressé donc je laisse comme avant pour l'instant
