### ISSUE TITLE
LP IFI 2024 > Mobile > Android / Chrome > Infos pratiques

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#30]
- en + de la flèche, est-ce-qu'on peut slider pour passer aux 2 autres documents ?
- possible d'agrandir un peu l'espace entre "infos pratiques" et les documents ?
![1000068365 (2)](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/76b30a43-bc13-4b3e-9e86-7a5ad2450f1d)

**Comment by jean-baptisteAZAN** [comment]
je m'en occuperai ce weekend pour le scroll, c'est pas possible avec mon code actuelle, je changerai

**Comment by Sahani14** [comment]
Pas possible de passer aux autres documents en slidant ?

Il y a un problème sur ce bloc.
- il faut que de base on ait le guide fiscal et le bulletin IFI de visibles ==> OK
- quand on clique sur la flèche à droite on peut accéder au RIB et au rapport annuel ==> OK
- quand on a le RIB t le rapport annuel, on ne doit pas pouvoir recliquer à droite ==> pas OK, actuellement il est possible de cliquer à droite même si on a pas de flèche

Je te mets un enregistrement d'écran pour que tu vois le bug.

https://github.com/adfinitas-app/curie-ifi20/assets/150721779/dd962329-b6bd-4384-b873-6afd4aec6679


En fait il faut qu'on ait juste ces 2 écrans : 

![Screenshot_2024-04-08-10-30-43-20_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/af2a1d03-6b58-444a-9117-4d697f1554f1)
![Screenshot_2024-04-08-10-30-47-99_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/39e54c56-1904-46f3-89d7-ff86f70735e8)

**Comment by jean-baptisteAZAN** [comment]
je pourrais pas implementer de manière viable et le scroll et le bouton pour aller au next sauf si je passe pas mal de temps dessus je tavoue, vaudrais mieux choisir un des 2. Je push avec le slide et tu regarde :)

**Comment by Sahani14** [comment]
Possible de rapprocher les 2 éléments un peu plus vers le centre pour que ça ne passe pas sous la flèche ?
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/c87d12bb-b5eb-4109-aa0f-3c90fd58c7cd)

--> pareil sur firefox et safari sur les petits écrans
