### ISSUE TITLE
LP IFI 2024 > Desktop > Timeline

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#32]
La proportion des textes est ok sur les écrans où c'était encore trop gros. Mais maintenant sur d'autres résolutions les dates sont trop petites :/ 
<img width="924" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/17fd481d-4386-428f-8153-96fb520d8d5b">

**Comment by jean-baptisteAZAN** [comment]
j'ai du inverse l'ordre de l'affichage des cartes, c'est le seul moyen que j'ai trouvé pour obtenir un affichage correct !
je pense que ca s'affiche bien sur les versions moins recents mais je ne peux pas tester car browserStack est down au moment ou j'essaye, n'hésite pas a me dire si c'est bon !

**Comment by Sahani14** [comment]
OK on fait comme ça, je te dis si c'est ok pour le client :)
