### ISSUE TITLE
LP IFI 2024 > Mobile > ancres projets

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#39]
Les 3 ancres projets fonctionnent bien sur desktop mais pas sur mobile.

J'ai testé sur : 
- Samsung Galaxy S22 > chrome
- Google Pixel 8 > firefox
- Iphone 15 > safari

**Comment by jean-baptisteAZAN** [comment]
j'ai testé les 3 et j'ai bien les bons projets avec les ancres en mobile pourtant
j'ai fais une petite video pour te montrer

**Comment by jean-baptisteAZAN** [comment]
Uploading Screen Recording 2023-12-30 at 09.29.14 (1).mp4…

**Comment by Sahani14** [comment]
Je ne vois pas la vidéo. De mon côté les ancres #projet1, #projet2, #projet3 ne fonctionnent pas

**Comment by jean-baptisteAZAN** [comment]
j'ai compris le soucis, je pense qu'on est bon
