### ISSUE TITLE
LP IFI 2024 > Desktop > Calculatrice

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#4]
Il manque les règles de calcul pour la calculatrice. Est-ce-que tu as la possibilité de reprendre la même chose que sur cette LP ? --> https://ifi.curie.fr/

**Comment by Sahani14** [comment]
- Le texte n'es pas bien centré dans les champs qui se remplissent automatiquement : 
<img width="895" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/02fa3e4b-5c66-4cc5-b2ba-45418c83e2f1">
<img width="932" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/9d651002-0b58-4bb8-9825-f5c690c3b861">

- Sur petit écran, la pop in est croppée, on ne voit pas les CTA don en entier : 
<img width="895" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/02fa3e4b-5c66-4cc5-b2ba-45418c83e2f1">
<img width="932" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/9d651002-0b58-4bb8-9825-f5c690c3b861">

- les 3 encarts ne sont pas de la même taille :  
<img width="802" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/29e15455-5e9d-4057-92d1-07f0cfcd6c80">

- possible de mettre un fond flouté comme celui qu'il y a à l'ouverture de la opo in 'impôt sur les sociétés" ?

**Comment by jean-baptisteAZAN** [comment]
j'ai traité les allignement , le flou tu voudrais le mettre ou ?

**Comment by Sahani14** [comment]
C'est pas totalement OK pour l'alignement, les textes dès champs qui se remplissent automatiquement ne sont pas bien centrés : 
<img width="900" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/a5ba2bb8-7a2f-4ad7-bb28-d79467168fb5">

Le fond flouté il faudrait le mettre sur l'écran derrière la calculatrice comme tu as fait pour la pop in impôt sur les sociétés stp

**Comment by Sahani14** [comment]
Le CTA de la calculatrice est tronquée sur petite résolution : 
<img width="1310" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/bec97f76-dc37-4103-bf8a-d0a421eb133f">

Est-ce-que tu peux mettre les mêmes liens de redirection que les CTA don du header stp ? 🙏 

Pour le flou le rendu n'est pas le même qu'avec la pop in impôt sur les sociétés. Possible d'avoir le même effet ?
