### ISSUE TITLE
LP IFI 2024 > Mobile > Problème affichage zone projets

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#40]
Quand je recette sur mon téléphone (Realme 8 > chrome), je ne vois plus la partie projets, j'ai ça à la place : 
![Screenshot_2024-04-09-10-20-34-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/47b21a6b-f17f-4788-8bab-84d339470808)

**Comment by jean-baptisteAZAN** [comment]
<img width="1709" alt="Screenshot 2024-04-09 at 10 44 33" src="https://github.com/adfinitas-app/curie-ifi20/assets/114654392/e1b01b78-87c3-4dc5-a2a0-21079578ef66">
peut être un soucis de cache, sur browser stack avec le relaxe ca fonctionne pourtant ?

**Comment by Sahani14** [comment]
J'ai le même soucis sur browserstack, par exemple ici sur Oppo A78 > chrome : 
![image](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/4f804e65-6767-44c2-8b57-166ef6844244)

J'ai l'impression que c'est à cause de l'ancre "calculatrice". Car quand j'arrive sur la LP via l'ancre et que je ferme la calculatrice, j'ai un soucis d'affichage de la zone projet même sur desktop. Aucun projet ne s'affiche par défaut : 

Uploading Partage d’écran - 2024-04-09 10 h 55 min 36 s.mp4…

**Comment by jean-baptisteAZAN** [comment]
je vais regarder ce cas

**Comment by jean-baptisteAZAN** [comment]
je pense avoir réglé le bug, si tu l'as de nouveau, tu peux me décrire dans quel ordre tu as procéder stp ? C'était un soucis de gestion des ancres !

**Comment by Sahani14** [comment]
J'ai toujours l
