### ISSUE TITLE
LP IFI 2024 > Desktop > taille des éléments

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#41]
Le premier retour concerne le « gabarit » de la page : j’ai l’impression que tous les éléments sont très zoomés : les boutons, les titres, les images, sont 2 fois plus gros que sur l’ancienne LP (et que les autres LP) : du coup, le problème, c’est que certains éléments sont trop gros pour être visible à l’écran sans scroller, cela dépasse la ligne de flottaison, notamment le bloc projet, tu verras les captures ci-dessous : j’ai laissé la résolution à 100 % puis baissé à 90 %.

100% : 
![image002](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/95bd776c-014f-46f7-b443-58d2bd0c228d)

90 % : 
![image003](https://github.com/adfinitas-app/curie-ifi20/assets/150721779/85951db7-28fc-42e7-ae84-3b01e7f8d65c)

Elle recette sur un PC portable > 1920 * 1080 > Windows > firefox

**Comment by jean-baptisteAZAN** [comment]
je vais regarder cela sur desktop, le soucis c'est que je reprend les tailles de la maquette pour chacun des elements donc bon

**Comment by Sahani14** [comment]
Il y a un soucis dans les tailles :
<img width="1251" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/99ffa48d-7a30-47f9-8d60-59bbeea2b6b1">

--> il faut que le texte paragraphe des 3 projets soit à la même taille
Là dans le projet 1 on voit que le paragraphe de gauche est écris en + gros que le paragraphe de droite
