### ISSUE TITLE
LP IFI 2024 > Desktop > Problème ancre

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#44]
Les ancres suivantes ne fonctionnent pas : 
- https://sure-snail.cloudvent.net/#projet2
- https://sure-snail.cloudvent.net/#projet3

Il y a un soucis avec l'ancre https://sure-snail.cloudvent.net/#Calculator
--> quand on arrive sur la page via cette ancre, la zone projet n'est pas visible, on voit que les onglets : 

https://github.com/adfinitas-app/curie-ifi20/assets/150721779/54e2d360-57b4-4605-bdf4-c0a9e6e05c2a

Possible de faire arriver l'ancre projet 1 au même niveau que l'ancre projects desktop ?

**Comment by jean-baptisteAZAN** [comment]
pour "Possible de faire arriver l'ancre projet 1 au même niveau que l'ancre projects desktop ?" non malheusement sinon. ca crée des conflits entre les differentes ancres
