### ISSUE TITLE
LP IFI 2024 > Liens footer

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#49]
Rajouter les liens RS dans le footer : 
- Mentions légales : https://curie.fr/page/mentions-legales
- Contact : https://curie.fr/webform/nous-contacter
- Linkedin : https://www.linkedin.com/company/institutcurie/
- X : https://twitter.com/institut_curie
- Facebook : https://fr-fr.facebook.com/InstitutCurie
- Instagram : https://www.instagram.com/institut_curie/

**Comment by Sahani14** [comment]
Les liens n'ont pas été rajoutés

**Comment by jean-baptisteAZAN** [comment]
petit oubli de mon coté ...

**Comment by Sahani14** [comment]
Toujours oublié non ? 🙈
