### ISSUE TITLE
LP IFI 2024 > Crédits

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#50]
Au clics sur "Crédits" dans le footer, il faudrait ouvrir une pop in crédits comme sur la LP https://ifi.curie.fr/

Sous "Réalisation", mettre : 
adfinitas

Sous "Crédits photos", mettre : 
© Institut Curie / Thibaut Voisin
© Institut Curie / Juery Franck
© Institut Curie / Beloncle Franck
© Institut Curie / Matias Manon

**Comment by Sahani14** [comment]
<img width="580" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/e5ba5900-7492-4ec5-8a37-bfe32e636c1a">


Possible de :
- augmenter l'opacité
- augmenter d'1 point la taille de "Réalisation" et "Crédits photos" + passer en gras
- diminuer de 2 points la taille des autres textes
- augmenter la taille de l'encart pour que tout le texte tienne dessus
- ne pas avoir les crédits sur 2 lignes à chaque fois

**Comment by Sahani14** [comment]
Je ne vois pas de différence, peut-être que tu n'as pas push ?

**Comment by Sahani14** [comment]
Si tu peux juste centrer les crédits et on sera bon :)

**Comment by Sahani14** [comment]
<img width="478" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/59aec397-22c3-41bd-b1ba-16ce8ceeb6fe">

--> soucis d'affichage sur petit écran

**Comment by Sahani14** [comment]
Le problème n'est pas réglé de mon côte 😞  
<img width="602" alt="image" src="https://github.com/adfinitas-app/curie-ifi20/assets/150721779/116786ad-6587-4665-b0e7-5f7832b0ec4b">

**Comment by jean-baptisteAZAN** [comment]
aie

**Comment by jean-baptisteAZAN** [comment]
je regarde
