### ISSUE TITLE
LP IFI 2024 > Mobile > onglets projet

### ISSUE THREAD

**Issue by Sahani14** [adfinitas-app/curie-ifi20#52]
Il y a des soucis au niveau des onglets projets : 
- lorsque l'on essaye de changer de projet et qu'on clique sur "Développer des immunothérapies inédites", ça ne fonctionne pas
- lorsque l'on clique sur "Accélérer la recherche grâce à deux équipements", on tombe sur le mauvais projet
- impossible d'accéder à tous les projets

https://github.com/adfinitas-app/curie-ifi20/assets/150721779/97499273-db1c-466b-8d88-cf1d06c3f5ff

**Comment by jean-baptisteAZAN** [comment]
normalement j'ai réglé ce bug, n'hesite pas a me re decrire le scenario si ca se reproduit

**Comment by Sahani14** [comment]
J'ai toujours le même bug
